---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/lemona41/terraxlocacoes.com.br/
    - /bin/cp -R index.html $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
